extensions:
 notes:
   searchDirs:
     - ~/Downloads
   destinationDirs:
     - ~/notes
   createSubDirs: false
 docx:
   searchDirs:
     - ~/Downloads
   destinationDirs:
     - ~/notes
   createSubDirs: false